version: "4"
services:
  db:
    build: ./timescaleDb
    container_name: db
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecret
      - POSTGRES_DB=mydb
  
  rhs:
    build: ./requestHandlerService
    container_name: rhs
    ports:
      - '3004:3004'
    env_file:
      - .env
  cs:
    build: ./consumerService
    container_name: cs
    env_file:
      - .env

  
